### PR TITLE
Fix AST::fromArray conversion of initial values (match initial to expected conversion)

### LINKED ISSUE #723: AST::fromArray converts DirectiveDefinitionNode->locations from array into NodeList
After running `AST::fromArray` on the output of `AST::toArray`, the `DirectiveDefinitionNode->locations` goes from an array to a NodeList. The `KnownDirectives` usage of `DirectiveDefinitionNode->locations` expects to work with an array so an error is generated instead.

```
Warning: array_map(): Expected parameter 2 to be an array, object given
```

https://github.com/webonyx/graphql-php/blob/4f3430990824ff410fe548102cb85f0c46442704/src/Language/AST/DirectiveDefinitionNode.php#L24-L25

https://github.com/webonyx/graphql-php/blob/4f3430990824ff410fe548102cb85f0c46442704/src/Utils/AST.php#L104-L116

https://github.com/webonyx/graphql-php/blob/4f3430990824ff410fe548102cb85f0c46442704/src/Validator/Rules/KnownDirectives.php#L74-L84

I'm not sure if the correct fix is to change KnownDirective to use `Utils::map`, adjust `AST::fromArray` to ensure it stays as an array, and/or to adjust the creation of `DirectiveDefinitionNode` to use a NodeList initially.

<details><summary>diffs for exposing the problem and a naive "fix"</summary>

The easiest way to expose this problem:
```diff
diff --git a/tests/Validator/KnownDirectivesTest.php b/tests/Validator/KnownDirectivesTest.php
index 38c190e..f35e94b 100644
--- a/tests/Validator/KnownDirectivesTest.php
+++ b/tests/Validator/KnownDirectivesTest.php
@@ -5,8 +5,10 @@ declare(strict_types=1);
 namespace GraphQL\Tests\Validator;
 
 use GraphQL\Error\FormattedError;
+use GraphQL\Language\Parser;
 use GraphQL\Language\SourceLocation;
 use GraphQL\Type\Schema;
+use GraphQL\Utils\AST;
 use GraphQL\Utils\BuildSchema;
 use GraphQL\Validator\Rules\KnownDirectives;
 
@@ -17,7 +19,7 @@ class KnownDirectivesTest extends ValidatorTestCase
 
     public function setUp() : void
     {
-        $this->schemaWithSDLDirectives = BuildSchema::build('
+        $this->schemaWithSDLDirectives = BuildSchema::build(AST::fromArray(AST::toArray(Parser::parse('
           directive @onSchema on SCHEMA
           directive @onScalar on SCALAR
           directive @onObject on OBJECT
@@ -29,7 +31,7 @@ class KnownDirectivesTest extends ValidatorTestCase
           directive @onEnumValue on ENUM_VALUE
           directive @onInputObject on INPUT_OBJECT
           directive @onInputFieldDefinition on INPUT_FIELD_DEFINITION
-        ');
+        '))));
     }
 
     private function expectSDLErrors($sdlString, $schema = null, $errors = [])
```

The easiest immediate "fix" (though having the type change doesn't seem correct?):
```diff
diff --git a/src/Validator/Rules/KnownDirectives.php b/src/Validator/Rules/KnownDirectives.php
index 6dbf849..758e861 100644
--- a/src/Validator/Rules/KnownDirectives.php
+++ b/src/Validator/Rules/KnownDirectives.php
@@ -36,6 +36,7 @@ use GraphQL\Language\AST\UnionTypeExtensionNode;
 use GraphQL\Language\AST\VariableDefinitionNode;
 use GraphQL\Language\DirectiveLocation;
 use GraphQL\Type\Definition\Directive;
+use GraphQL\Utils\Utils;
 use GraphQL\Validator\ASTValidationContext;
 use GraphQL\Validator\SDLValidationContext;
 use GraphQL\Validator\ValidationContext;
@@ -76,11 +77,11 @@ class KnownDirectives extends ValidationRule
                 continue;
             }
 
-            $locationsMap[$def->name->value] = array_map(
+            $locationsMap[$def->name->value] = Utils::map(
+                $def->locations,
                 static function ($name) : string {
                     return $name->value;
-                },
-                $def->locations
+                }
             );
         }
 
```

</details>

### PR DESCRIPTION
**Pull request by zimzat**
- Parse `DirectiveDefinitionNode->locations` as `NodeList<NamedNode>`
- Parse `Parser::implementsInterfaces` as `NodeList<NamedTypeNode>`
- Update signature of `Parser::unionMemberTypes` to match actual `NodeList<NamedTypeNode>`

Fixes #723

Note: I wasn't sure how to address the phpstan error so I updated the baseline. I can revisit this if necessary.

```
 ------ ----------------------------------------------------------------------- 
  Line   src/Validator/Rules/KnownDirectives.php                                
 ------ ----------------------------------------------------------------------- 
         Ignored error pattern #^Only booleans are allowed in a negated         
         boolean, array<string\>\|null given\.$# in path                        
         /home/zimzat/files/sources/graphql-php/src/Validator/Rules/KnownDirec  
         tives.php was not matched in reported errors.                          
  102    Only booleans are allowed in a negated boolean, array|null given.      
 ------ ----------------------------------------------------------------------- 
```

### CODE REVIEW

File: src/Language/Parser.php [hunk 1]
```diff
@@ -1220,10 +1220,8 @@ private function parseObjectTypeDefinition() : ObjectTypeDefinitionNode
      * ImplementsInterfaces :
      *   - implements `&`? NamedType
      *   - ImplementsInterfaces & NamedType
```
Comment (spawnia) [inline src/Language/Parser.php:1222]:
```suggestion
     *   - ImplementsInterfaces & NamedType
     *
     * @return NodeList<NamedTypeNode>
```

File: src/Language/Parser.php [hunk 2]
```diff
@@ -1746,11 +1744,9 @@ private function parseDirectiveDefinition() : DirectiveDefinitionNode
     }
 
     /**
-     * @return NameNode[]
-     *
      * @throws SyntaxError
```
Comment (spawnia) [inline src/Language/Parser.php:1747]:
```suggestion
     * @return NodeList<NameNode>
     *
     * @throws SyntaxError
```

**Review by spawnia — APPROVED** [review]
This makes the Parser more self-consistent, looks good to me.

**Comment by zimzat** [comment]
Thanks @spawnia. I removed instead of updated the `@return` because other places didn't have them and nothing was complaining, though I agree there's benefit in having them. :+1:

**Comment by zimzat** [comment]
@spawnia It looks like phpcs marks those as duplicate information errors :disappointed: 

Should I remove them again, or is there something I could do in PHPCS to allow for them?

**Comment by spawnia** [comment]
> Should I remove them again, or is there something I could do in PHPCS to allow for them?

Maybe we can fix that in the future, let's remove it for now to keep this PR focused.

**Comment by zimzat** [comment]
Done :+1: Thanks!

**Review by simPod — APPROVED** [review]

**Comment by vladar** [comment]
Thanks for the fix!
